
[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino

board_build.core = earlephilhower
board_build.filesystem = rp2040

monitor_speed = 115200
upload_speed = 115200
build_flags = -O3

; lib_deps =