// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------- //
// hub75_data //
// ---------- //

#define hub75_data_wrap_target 0
#define hub75_data_wrap 1
#define hub75_data_pio_version 0

static const uint16_t hub75_data_program_instructions[] = {
            //     .wrap_target
    0x6106, //  0: out    pins, 6         side 0 [1]
    0x7162, //  1: out    null, 2         side 1 [1]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program hub75_data_program = {
    .instructions = hub75_data_program_instructions,
    .length = 2,
    .origin = -1,
    .pio_version = hub75_data_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config hub75_data_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + hub75_data_wrap_target, offset + hub75_data_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}

static inline void hub75_data_program_init(PIO pio, uint sm, uint offset, uint data_pin_base, uint clk_pin) {
    pio_sm_config c = hub75_data_program_get_default_config(offset);
    // Set pin RGB (6 pin kontigu) sebagai output PIO
    sm_config_set_out_pins(&c, data_pin_base, 6);
    // Set pin CLK sebagai side-set
    sm_config_set_sideset_pins(&c, clk_pin);
    // Hubungkan pin ke PIO
    for (int i = 0; i < 6; i++) {
        pio_gpio_init(pio, data_pin_base + i);
    }
    pio_gpio_init(pio, clk_pin);
    // Set arah pin sebagai output
    pio_sm_set_consecutive_pindirs(pio, sm, data_pin_base, 6, true);
    pio_sm_set_consecutive_pindirs(pio, sm, clk_pin, 1, true);
    // Konfigurasi shift register: 
    // Shift ke kanan (true), autopull aktif (true), threshold 8 bit
    sm_config_set_out_shift(&c, true, true, 8); 
    // Set clock divider (sesuaikan kecepatan matrix, 10-20MHz biasanya aman)
    float div = (float)clock_get_hz(clk_sys) / 20000000; 
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

